name: "Memories Can't Wait"
favicon: null
layout_spectrum: 0.16968127712607384
typography_spectrum: 0.34847666951827705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3efd4'
    - '#114d31'
    - '#6496b9'
    - '#11becf'
    - '#9fc87c'
  brandStrength: 0.5
  lightness: 0.3829470977652818
  saturation: 0.5496673530433327
  rhythmicContrast: 0.3327100947499275
purpose: []
